"""Filesystem syscalls: write_file + scaffold_repo.

These are domain-agnostic. ``scaffold_repo`` builds a conventional, runnable project tree
(folders, README, a FastAPI skeleton, a test, and an eval stub) from a small spec the
agent passes — the "real scaffolded product repo appears on disk" payoff of the MVP demo.
All writes are sandboxed to the run workspace by ``safe_join``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .base import safe_join


class WriteFileTool:
    name = "write_file"

    def invoke(self, root: Path, *, path: str, content: str = "", **_: Any) -> dict:
        target = safe_join(root, path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return {"tool": self.name, "path": str(target.relative_to(root.resolve()))}


class ScaffoldRepoTool:
    name = "scaffold_repo"

    def invoke(
        self,
        root: Path,
        *,
        name: str,
        slug: str | None = None,
        summary: str = "",
        endpoints: list[dict] | None = None,
        entities: list[dict] | None = None,
        base: str = "scaffold",
        **_: Any,
    ) -> dict:
        slug = slug or _slugify(name)
        repo = safe_join(root, f"{base}/{slug}")
        endpoints = endpoints or []
        entities = entities or []

        files: dict[str, str] = {
            "README.md": _readme(name, summary, endpoints, entities),
            "requirements.txt": "fastapi>=0.111\nuvicorn[standard]>=0.30\npydantic>=2.7\n",
            "pyproject.toml": _pyproject(slug),
            ".gitignore": "__pycache__/\n*.pyc\n.venv/\n.env\n",
            "app/__init__.py": "",
            "app/main.py": _fastapi_main(name, endpoints),
            "app/models.py": _models(entities),
            "tests/__init__.py": "",
            "tests/test_health.py": _test_health(),
            "evals/run_eval.py": _eval_stub(name),
        }
        written: list[str] = []
        for rel, content in files.items():
            target = repo / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            written.append(str(target.relative_to(root.resolve())))

        return {
            "tool": self.name,
            "repo": str(repo.relative_to(root.resolve())),
            "files": sorted(written),
            "fileCount": len(written),
        }


def _slugify(text: str) -> str:
    out = "".join(c.lower() if c.isalnum() else "-" for c in text).strip("-")
    while "--" in out:
        out = out.replace("--", "-")
    return out or "product"


def _readme(name: str, summary: str, endpoints: list[dict], entities: list[dict]) -> str:
    ep = "\n".join(f"- `{e.get('method','GET')} {e.get('path','/')}` — {e.get('purpose','')}"
                   for e in endpoints) or "- (none yet)"
    en = "\n".join(f"- **{e.get('name','Entity')}** — {e.get('fields','')}"
                   for e in entities) or "- (none yet)"
    return (
        f"# {name}\n\n{summary}\n\n"
        "> Scaffolded by **ANDS Forge OS**. Runnable FastAPI skeleton with a health "
        "check, a test, and an eval stub.\n\n"
        "## Quickstart\n\n"
        "```bash\npip install -r requirements.txt\n"
        "uvicorn app.main:app --reload\n```\n\n"
        f"## API endpoints\n\n{ep}\n\n## Domain entities\n\n{en}\n"
    )


def _pyproject(slug: str) -> str:
    return (
        "[project]\n"
        f'name = "{slug}"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.11"\n'
        'dependencies = ["fastapi>=0.111", "uvicorn[standard]>=0.30", "pydantic>=2.7"]\n\n'
        "[tool.pytest.ini_options]\n"
        'testpaths = ["tests"]\n'
    )


def _fastapi_main(name: str, endpoints: list[dict]) -> str:
    routes = ['@app.get("/health")\ndef health():\n    return {"status": "ok"}\n']
    for e in endpoints:
        method = str(e.get("method", "GET")).lower()
        path = e.get("path", "/")
        fn = "endpoint_" + _slugify(f"{method}_{path}").replace("-", "_")
        routes.append(
            f'@app.{method}("{path}")\n'
            f"def {fn}():\n"
            f'    """{e.get("purpose", "")}"""\n'
            f'    return {{"todo": "implement {path}"}}\n'
        )
    body = "\n\n".join(routes)
    return (
        '"""Scaffolded FastAPI app — generated by ANDS Forge OS."""\n\n'
        "from fastapi import FastAPI\n\n"
        f'app = FastAPI(title="{name}")\n\n\n'
        f"{body}"
    )


def _models(entities: list[dict]) -> str:
    if not entities:
        return (
            '"""Domain models (scaffold). Generated by ANDS Forge OS."""\n\n'
            "from pydantic import BaseModel\n\n\n"
            "class Placeholder(BaseModel):\n    id: str\n"
        )
    blocks = ['"""Domain models (scaffold). Generated by ANDS Forge OS."""',
              "", "from pydantic import BaseModel", "", ""]
    for e in entities:
        cls = "".join(p.capitalize() for p in _slugify(e.get("name", "Entity")).split("-"))
        blocks.append(f"class {cls}(BaseModel):")
        blocks.append("    id: str")
        blocks.append("")
    return "\n".join(blocks)


def _test_health() -> str:
    return (
        "from fastapi.testclient import TestClient\n\n"
        "from app.main import app\n\n"
        "client = TestClient(app)\n\n\n"
        "def test_health():\n"
        '    resp = client.get("/health")\n'
        "    assert resp.status_code == 200\n"
        '    assert resp.json()["status"] == "ok"\n'
    )


def _eval_stub(name: str) -> str:
    return (
        "#!/usr/bin/env python3\n"
        '"""Eval stub — generated by ANDS Forge OS. Extend with golden cases + a gate."""\n\n'
        "from __future__ import annotations\n\n"
        "import sys\n\n\n"
        "def run() -> int:\n"
        f'    print("Eval stub for {name}: add golden cases and a regression gate.")\n'
        "    return 0\n\n\n"
        'if __name__ == "__main__":\n'
        "    sys.exit(run())\n"
    )


def write_json(root: Path, path: str, data: Any) -> str:
    """Helper for callers that want to drop a JSON file (not a Tool, used internally)."""
    target = safe_join(root, path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return str(target.relative_to(root.resolve()))
